### PR TITLE
chore: react ns7 updates

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Review by shirakaba — APPROVED** [review]
RNS v2.0.0 is now released, so this will work.

The package name for this template has apparently been changed from `tns-template-blank-react` to `@nativescript/template-blank-react`, and I've found that I don't have permission to publish `@nativescript/template-blank-react`. Will merging this to master trigger a publish? If so, please go ahead.

```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@nativescript%2ftemplate-blank-react - Not found
npm ERR! 404 
npm ERR! 404  '@nativescript/template-blank-react@7.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by NathanWalker** [comment]
Excellent thanks @shirakaba we can help publish it shortly.
Scoping it allows {N} 7 to use new template while still allowing the old template to work with old cli 👍

**Comment by shirakaba** [comment]
@NathanWalker It seems that a package versioned as v7.0.1 has [already been published to npm](https://www.npmjs.com/package/@nativescript/template-blank-react) – did we do that during our call? I don't remember. Just checking whether we need to bump it once more to 7.0.2 and publish or whether that work has already been done.

**Comment by NathanWalker** [comment]
We’ll publish a bumped version 👍

**Pull request merged**
