### PR TITLE
feat: Update React template to include RNS Navigation

### PR DESCRIPTION
**Pull request by shirakaba**
Note: I found that I was not allowed to publish to `@nativescript/template-blank-react` (I got an error message like "the path does not exist") so I'm not sure what the procedure is. I've verified that it works by publishing to `tns-template-blank-react` and trying it out, so I have been able to test this release..

### CODE REVIEW

**Review by NathanWalker — APPROVED** [review]

**Comment by NathanWalker** [comment]
Thanks @shirakaba we’ll get this published later today -  not sure on the publish error, we’ll check that too.

**Comment by shirakaba** [comment]
Thanks @NathanWalker! The exact publishing error was:

```
$ cd packages/template-blank-react
$ npm publish
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@nativescript%2ftemplate-blank-react - Not found
npm ERR! 404 
npm ERR! 404  '@nativescript/template-blank-react@7.0.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jamie/.npm/_logs/2020-10-24T14_41_30_338Z-debug.log
```

**Comment by NathanWalker** [comment]
@shirakaba published now 👍

**Comment by shirakaba** [comment]
@NathanWalker Awesome, thanks!

**Pull request merged**
