### PR TITLE
[DO NOT MERGE] chore: update configs to androidx

### PR DESCRIPTION
**Pull request by dtopuzov**
Migrate to AndroidX

### CODE REVIEW

**Comment by dtopuzov** [comment]
test tns-android#androidx tns-core-modules#androidx nativescript-ui-chart#androidx nativescript-ui-dataform#androidx nativescript-ui-gauge#androidx nativescript-ui-listview#androidx nativescript-ui-sidedrawer#androidx

**Comment by dtopuzov** [comment]
test tns-android#androidx tns-core-modules#androidx nativescript-ui-chart#androidx nativescript-ui-dataform#androidx nativescript-ui-gauge#androidx nativescript-ui-listview#androidx nativescript-ui-sidedrawer#androidx

**Comment by dtopuzov** [comment]
test tns-android#androidx tns-core-modules#androidx nativescript-ui-chart#androidx nativescript-ui-dataform#androidx nativescript-ui-gauge#androidx nativescript-ui-listview#androidx nativescript-ui-sidedrawer#androidx

**Comment by SvetoslavTsenov** [comment]
test android#6.0.0-2019-06-05-002854-01 tns-core-modules#androidx nativescript-ui-chart#androidx nativescript-ui-dataform#androidx nativescript-ui-gauge#androidx nativescript-ui-listview#androidx nativescript-ui-sidedrawer#androidx

**Pull request merged**
